plugins {
  id "java-gradle-plugin"
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.gradle.publish)
  alias(libs.plugins.lint)
}

dependencies {
  implementation gradleApi()

  lintChecks libs.androidx.gradleLintChecks

  testImplementation libs.junit
}

compileKotlin {
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11
  }
}
compileTestKotlin {
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11
  }
}
java {
  sourceCompatibility JavaVersion.VERSION_11
  targetCompatibility JavaVersion.VERSION_11
}

group = 'com.jraska.module.graph.assertion'

gradlePlugin {
  website = 'https://github.com/jraska/modules-graph-assert'
  vcsUrl = 'https://github.com/jraska/modules-graph-assert'

  plugins {
    modulesGraphAssert {
      id = 'com.jraska.module.graph.assertion'
      version = '2.9.0'
      displayName = 'Modules Graph Assert'
      description = 'Gradle plugin to keep your modules graph healthy and lean.'
      implementationClass = 'com.jraska.module.graph.assertion.ModuleGraphAssertionsPlugin'
      tags.addAll('graph', 'assert', 'build speed', 'android', 'java', 'kotlin', 'quality', 'multiprojects', 'module')
    }
  }
}
